### ISSUE TITLE
Improve organization of samples?

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#109]
I think the samples would be a more useful if there was more organization.

My first idea is to create folders to hold the projects for each sample, which would look like
```
- Samples
  - SingleCounter
    - SingleCounter
    - SingleCounter.Views
  - SubModel
    - SubModel
    - SubModel.Views
```

If that seems like a good idea, then I have some follow ups to it.

One idea is prefixing the folder names with two digits so they become sorted roughly in the order of increasing complexity.  When the folders are closed, that could look like
```
- Samples
  - 01 SingleCounter
  - 02 SubModel
```

Instead of prefixing with two digits, another suggestion is grouping samples into categories such as "Basic", "Intermediate", and "Advanced", which could look like
```
- Samples
  - 01 Basic
    - SimpleCounter
      - SimpleCounter
      - SimpleCounter.Views
  - 02 Intermediate
  - 03 Advanced
    - EventBindingsAndBehaviors
      - EventBindingsAndBehaviors
      - EventBindingsAndBehaviors.Views
```

I can provide my opinion about categorization or sorting order.  In any case, I am willing to make a PR for this.

**Comment by cmeeren** [comment]
Thanks for the suggestion!

As for your first idea: I personally don't see the need to group two and two projects when they're shown next to each other anyway. I find it easier to select and start different projects/samples when I don't have to expand and collapse folders all the time. But if you really want to group them like this and think it's a good idea, I can live with it.

As for your other suggestions re. complexity, order etc:

I have previously thought about the need for some information about the samples. However, I don't think directory structure is the way to go for this, since that locks you down to a single hierarchy and a single way of categorizing the projects, and requires artificially modifying names in order to conform to a non-name-based structure. I'd rather keep the directory structure simple and more or less flat. I think a readme in the sample directory would be much better. The readme could present the projects in a useful order, and contain a short description of each. If that's something you'd like to work on, feel free!

**Comment by bender2k14** [comment]
Since you have mixed feelings about this, I won't make any change at this time.

> if we should ever get more complex samples with more than two projects, e.g. for demonstrating different project structures, I'm certainly open to it, particularly for those projects.

Indeed.  Another example that I think would be useful (or could just be part of the project structure examples) is how to use design time view models.  The [documentation of this](https://github.com/elmish/Elmish.WPF#can-i-use-design-time-view-models) on the home page was great, and a sample showing the final product would be a nice addition.

Another reason to reconsider this is if the number of samples continues to increase, which I think would be a good thing.

**Comment by cmeeren** [comment]
Yep, I'm certainly open for discussing folder-per-sample when the situation changes. 👍

**Comment by cmeeren** [comment]
In any case, a README in the `Samples` folder would be helpful. Leaving this issue open.

**Comment by bender2k14** [comment]
The [tutorial](https://github.com/elmish/Elmish.WPF/blob/master/TUTORIAL.md) is great.  No need for this now.
