### ISSUE TITLE
Added to fsharp.org/use/desktop-apps/

### ISSUE THREAD

**Issue by dsyme** [elmish/Elmish.WPF#204]
Hi all,

I've added Elmish.WPF as a listed way of making Windows desktop apps here: https://fsharp.org/use/desktop-apps/.  I'd expect this to generate a fair bit of traffic over time.

Could you take a look and check the info, and keep it up to date byt sending PRs?  Please also make sure your getting started experience continues to be simple, accurate and well-documented.

Great work on the framework 👍 👍 

Thanks
Don

**Comment by cmeeren** [comment]
Thanks! Current info looks good ☺ We'll make sure to stay on top of the getting started experience.

**Comment by cmeeren** [comment]
@dsyme I took the liberty of designing a logo, using the F# logo geometric primitives/colors to evoke the [WPF logo](https://www.google.com/search?tbm=isch&q=wpf%20logo). Is this an acceptable use of the F# logo? (Related case that was approved: https://github.com/cmeeren/Felicity/issues/1)

<img src="https://raw.githubusercontent.com/elmish/Elmish.WPF/9f8fd2f951f6420f91dcc5bfb81cc6de5519b65e/elmish-wpf-logo.png" />

**Comment by dsyme** [comment]
@cmeeren Hmmm... I'd normally say "yes" straight away but this one took me by surprise - it feels like an odd one because it looks like a twist/distortion of the F# logo, without the "adornment" that most projects use.

**Comment by cmeeren** [comment]
I see. Please check out https://github.com/cmeeren/Felicity/issues/1 – the reasoning there is applicable here, too, and that logo was approved by @ReedCopsey.

**Comment by bender2k14** [comment]
I friend of mine is an expert in this kind of thing.  He had an idea for what an Elmish.WPF logo (derived from the F# and WPF logos) would look like.  He will share them in a comment soon.

**Comment by MrMattSim** [comment]
![elmish-wpf-logo-shade](https://user-images.githubusercontent.com/10426122/79668964-57641900-8186-11ea-8a15-7a0cbad23a02.png)

Thanks @bender2k14 . The multi-tone wave often associated with WPF is actually an old ".net" logo more generally. So rather than using the wave, I've design the logo above to reference the target ecosystem by adapting the familiar "perspective frame" motif found across a variety of Windows/Microsoft products. The take-away message being something like: "F# for Windows apps"

**Comment by cmeeren** [comment]
Very nice, @MrMattSim! I like that better than my suggestion. I suggest we go with your logo.

**Comment by cmeeren** [comment]
@MrMattSim Is there anything I should know about? Any terms, crediting, etc.? The version you posted is sufficiently high-res for the purposes here, but would it be possible to get the original vector format (that I assume exists) to check into the repo? Always nice to have. :)

**Comment by MrMattSim** [comment]
Thanks! It's all yours: I hereby transfer all copyrights to the Elmish.WPF project. No formal credit needed. Maybe just a shout-in the readme 😎

I'll prep a clean master file. Shall I just make a PR to replace the two assets: elmish-wpf-logo.png and .psd

**Comment by cmeeren** [comment]
A PR would be nice!
* `elmish-wpf-logo.png`: Due to how GH image layout works, most notably the inability to set padding/margin in HTML, it would be great if it has "built in" 5% padding on the left/bottom. It can be tightly trimmed on the top/right. There is no need to make it square.
* Additionally, there's a file in `src/Elmish.WPF` to replace. This is used for NuGet. As the name implies, it's 128x128. AFAIK it must be square, but does not need any padding.

**Comment by dsyme** [comment]
Cool; job

> Please check out cmeeren/Felicity#1 – the reasoning there is applicable here, too, and that logo was approved by @ReedCopsey. 

I'm not the one to approve/confirm (Reed or FSSF board members are) - but from my personal perspective the Felicity one looks fine to me because it is additive (doesn't have the "distortive" feeling of the one above).

**Comment by ReedCopsey** [comment]
@cmeeren I'd agree with @dsyme 's rationale here - the original logo borders on being the original but altered in merely "shape or proportions" but the new one (which I also personally prefer) definitely seems like it's an addition on top of (parts of) the main logo. I'd definitely say the new one would be fine to use.

**Comment by cmeeren** [comment]
Great, thanks for weighing in! ☺

**Comment by dsyme** [comment]
The only other comment I'd make is that most MVU logos use circularity, e.g. see discussion here https://github.com/fsprojects/Fabulous/issues/710#issuecomment-616707911

I think using this theme somehow might be nice for Elmish.WPF, to emphasize the Elmish architecture (more than the current proposal to emphasize F# and WPF)

**Comment by cmeeren** [comment]
Thanks, @MrMattSim! I really appreciate the work you do.

Personally I think the logo is great as-is. Technically speaking, Elmish.WPF isn't "real MVU" due to having to use static views, so I don't feel there's a strong need to evoke Elm itself with the logo.

However, I will happily defer to your judgement if you think the Elm palette version works better. If so, feel free to send a PR and I'll accept it.

**Comment by cmeeren** [comment]
A consideration to take into account is how other F# MVU frameworks do it. For example, the Fabulous logo/discussion @dsyme linked to shows a logo using the Elmish palette. That could be an argument for doing the same thing here (or not).

Any feedback is welcome. I don't currently have any strong opinions either way.

**Comment by dsyme** [comment]
> I couldn't find any other examples of MVU projects whose logos were circular. Do you have more? I love seeing variations on a theme.

* React and React Native 

![image](https://user-images.githubusercontent.com/7204669/79983710-0a42b880-84a0-11ea-914c-2546ad408c57.png)

* Redux 

![image](https://user-images.githubusercontent.com/7204669/79984461-2004ad80-84a1-11ea-9b6c-0c38bed174d3.png)

* Flow 

![image](https://user-images.githubusercontent.com/7204669/79983971-6d344f80-84a0-11ea-8db1-881297b9a3c5.png)

* Proposal for Fabulous 

<img src="https://user-images.githubusercontent.com/6429007/79797765-22a7bb80-8358-11ea-9b7f-5d4f0e69b3b7.png" height="200" />

They are all "MVU-like", not actually Elm or Elmish.  However I think this is a very good logo theme for MVU and MVU-like architectures, which nearly always explain the whole concept by contrasting MVM "objects and blocks" with a circlur flow, e.g. like this:

![image](https://user-images.githubusercontent.com/7204669/79984185-bab0bc80-84a0-11ea-9266-af21cc74b127.png)
