### ISSUE TITLE
How do I parameterize the init function?

### ISSUE THREAD

**Issue by ScottHutchinson** [elmish/Elmish.WPF#209]
The `Program.mkSimpleWpf` function expects an `init` function with the signature `unit -> 'model`, but I need to initialize the model based on input arguments.

How do I do it?

Thanks

**Comment by bender2k14** [comment]
[Partial function application](https://en.wikipedia.org/wiki/Partial_application).

For example, suppose we wanted to initialize the `SubModelSelectedItem` sample based on input arguments instead of hardcoding the initially selected item to `4`.

https://github.com/elmish/Elmish.WPF/blob/b4decde84695fca769c394d23a99a53f33087088/src/Samples/SubModelSelectedItem/Program.fs#L15-L17

Then you can change that code to
```
let init selection () =
  { Entities = [0 .. 10] |> List.map (fun i -> { Id = i; Name = sprintf "Entity %i" i})
    Selected = Some selection }
```

and
https://github.com/elmish/Elmish.WPF/blob/b4decde84695fca769c394d23a99a53f33087088/src/Samples/SubModelSelectedItem/Program.fs#L46
to
```
Program.mkSimpleWpf (init 4) update bindings
```

**Comment by ScottHutchinson** [comment]
Brilliant! That worked great. Thanks
