### ISSUE TITLE
Elmish.WPF vs ReactiveUI

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#248]
I just came across [ReactiveUI](https://github.com/reactiveui/reactiveui).

Does anyone know how this compares to Elmish.WPF?

If not, I might study it eventually and report back to share what I learned.

**Comment by cmeeren** [comment]
I experimented a bit with ReactiveUI long ago before I encountered Elmish and even F#. I tested it as an alternative to MVVM. I found it fairly complicated. I ultimately abandoned it. I remember coming across a blog post (which I'm not able to find at the moment) which said something to the effect that while in theory ReactiveUI sounds robust, in practice you'll still encounter weird problems due to the temporal nature of all the data streams you are managing, combing, etc., and that often, bug fixes boil down to "I can't find anything, I'll just try inserting a debounce/throttle/etc. here and see if it works, and hope it still does in production".

Let me again reiterate that I haven't used it for anything serious (a complex app). But my impression is that there's a simplicity, consistency, and elegance to MVU that I just don't see ReactiveUI competing with.

**Comment by lioobayoyo** [comment]
I'm echoing on cmeeren's comment.

We are currently in a project where we started with WPF / ReactiveUI to get some functional "safety and clarity". I still believe it helps to get behaviors in reaction of changes of properties more neat and more centralised, but handling proper threading issues becomes another kinn of mess.

You want also to be careful of synchronisation of your flow of data, and in our case it has somehow become another kind of spaghetti code as well, and hard to read for a new developer.

You still need states at some point, or at least it felt like it. So we have somehting half-functional.

We are in the process of porting to F# and we hope we will get a more "natural" codebase with this.. I'll try to get you posted on the results when we reach a pruciton point.

**Comment by TysonMN** [comment]
Hello @lioobayoyo.  Thanks for sharing your experience with ReactiveUI.

After porting to F#, is switching to Elmish.WPF something that is being considered?

**Comment by lioobayoyo** [comment]
That is already in progress! We still want to keep WPF, and Elmish.WPF sounded a reasonable option. Edited my first message.

**Comment by TysonMN** [comment]
Excellent!  Good luck :D

**Comment by TysonMN** [comment]
Closing the issue, but everyone is welcome to continue the discussion.

**Comment by atlemann** [comment]
I've used Reactive UI for a few years on a fairly big project, with great success. It's infinitely better than working with the property changed events directly. At least when we're stuck with the MVVM pattern, it simplifies things a lot. You have to spend some time getting used to working with observables though. Combine it with https://dynamic-data.org/ and you have some pretty powerful tools to work with.

**Comment by BentTranberg** [comment]
I read this issue thread this morning, and has been researching everything Reactive I can find for most of the day. I haven't found nice support for F# when using ReactiveUI, but at least I got that simple starter demo translated. At this stage I'm just learning, and guess I'll need a few days before I can tell whether this is an alternative or a complement to Elmish.WPF.

I agree about the simplicity of Elmish, and I don't think I want to replace that. I'm thinking that perhaps "something reactive" can simplify GUI matters outside of the Elmish loop, but my thoughts about this are very fuzzy right now.
