### ISSUE TITLE
Include sample with an F# startup project

### ISSUE THREAD

**Issue by TysonMN** [elmish/Elmish.WPF#261]
This [question](https://stackoverflow.com/questions/63348787/how-to-start-multiple-windows-from-f-using-elmish-wpf) on StackOverflow is about how to use Elmish.WPF with an F# project as the entry point.

In PR #249, I just switched all the samples to use the C# project as the entry point in order to enable support for design-time data binding.

Maybe we should have at least one sample that has F# as the entry point.

**Comment by cmeeren** [comment]
I have nothing against that. I requested the poster come here and describe why they want an F# startup project. I'm curious what the motivation is.

**Comment by BentTranberg** [comment]
I've used C# startup for a long time, and is not aware of anything. For F# startup I know I've had several issues. One of them I believe was about running the application as admin by default, but I'm not quite sure my memory is good. Other issues had to do with resources placed in the startup project, when F#. I can try to recreate these problems if there's an interest, but I guess there isn't.

I'm happy you switched to C# as entry point.

**Comment by bender2k14** [comment]
I am interested, but don't beat yourself up if it is difficult to reproduce

**Comment by awaynemd** [comment]
My reasoning for posting the question was to follow as close as possible "Getting Elmish in .NET with Elmish.WPF" by Matt Eland. For the reasoning mentioned above, I can see why this now maybe obsolete. Thanks.

**Comment by bender2k14** [comment]
For reference: link to [Getting Elmish in .NET with Elmish.WPF](https://killalldefects.com/2019/12/30/getting-elmish-in-net-with-elmish-wpf/)

**Comment by MicaelMor** [comment]
When I started using Elmish.WPF a lot of the examples I found had F# as the startup project, so that might be where the issue lies, in fact only remember seeing one mention of having C# as the starting point (think it was on the project documentation).

Personally I moved from an F# starting project which was the "standard" at the time, to C# simply so I could use value converters created in F# on the C#, and ofc as the transition of the samples to C# shows, another big advantage is design time models.

The only issue I have found since then is with calling windows, because the F# project does not inherit the C# project it cannot call them directly, the C# project needs to pass them to F#, but the samples already covers a basic (if not super extendable) way of solving that issue.

**Comment by cmeeren** [comment]
> The only issue I have found since then is with calling windows, because the F# project does not inherit the C# project it cannot call them directly, the C# project needs to pass them to F#, but the samples already covers a basic (if not super extendable) way of solving that issue.

That's right. There's no way around that. You can, of course, define an interface in the F# project with methods that construct all your windows and accept that interface as a parameter to `update`, and implement that interface in the C# project. That way you reduce the amount of arguments to `update`, but otherwise it's essentially the same, so do whatever floats your boat.

**Comment by TysonMN** [comment]
This issue is subsumed by issue #325.
