### ISSUE TITLE
Unclear on how the bindings are checked (recomputed)

### ISSUE THREAD

**Issue by MecuSorin** [elmish/Elmish.WPF#269]
My scenario is a combobox that is bind to a list of objects of a form similar to 
```type Program = { label: string; iterations: int }```  and I want to change the current selected list item **iterations**.

The problem is the fact that after I attempt to change the value of the **iterations**, the model is oscillating between the old implicit program record and the new one (messages of type **SelectImplicitProgram** triggered by the **SelectedItem** of the combobox).

```
"Programs" |> Binding.subModelSeq(
    (fun (m, _) -> BindingHelpers.programsList m)
    , id
    , fun () -> [
        "ProgramName" |> Binding.oneWay (fun (_, p) -> p.label)
        "ProgramIterations" |> Binding.oneWay (fun (_, p) -> p.iterations)
    ])
"ImplicitProgram" |> Binding.subModelSelectedItem (
    "Programs"
    , (fun (m, _) -> BindingHelpers.implicitProgram m |> ValueOption.Some)
    , (fun pVOption (m, _) ->
        ValueOption.defaultValue (BindingHelpers.implicitProgram m) pVOption
        |> ConfigurationForm.SelectImplicitProgram
        |> ConfigurationFormMsg)
    , debounceMessage 200)
"ImplicitProgramIterations" |> Binding.twoWay(
    (fun (m, _) -> BindingHelpers.implicitProgramIterations m)
    , fun newVal m -> ConfigurationForm.ChangeImplicitProgramIterations newVal |> ConfigurationFormMsg
    , debounceMessage 150)
```

The xaml looks like:
```
                   <ComboBox SelectedValue="{Binding ImplicitProgram}" ItemsSource="{Binding Programs}" >
                        <ComboBox.ItemTemplate>
                            <DataTemplate>
                                <StackPanel Orientation="Horizontal">
                                    <TextBlock Text="{Binding ProgramName}" />
                                </StackPanel>
                            </DataTemplate>
                        </ComboBox.ItemTemplate>
                    </ComboBox
                    <xctk:IntUpDown Value="{Binding Path=ImplicitProgramIterations, Mode=TwoWay}" />
```

How I can invalidate the **Program** and **ImplicitProgram** bindings when the implicit program is being replaced in the model? Don't have many programs so no optimizations are needed

I chose the correct binding for my task at hand?

**Comment by MecuSorin** [comment]
I know now what was the problem with my code:
```ValueOption.defaultValue (BindingHelpers.implicitProgram m) pVOption``` from ImplicitProgram binding setter. 
Somehow is still firing 2 messages, but I can send a SelectImplicitProgram and a Noop messages.

**Comment by cmeeren** [comment]
Glad you solved it. Note that it is easier for us to help if we have a complete repro solution.

I see that you are using the `wrapDispatch` parameter. Note that this parameter is [being removed in v4](https://github.com/elmish/Elmish.WPF/issues/253). Let us know in that issue if that will cause problems for you.

**Comment by MecuSorin** [comment]
As you suspect, the code shared was just an simplified example from a more complex beast.

Why is removed? For my project will be a bad thing, is a very nice commodity to reduce the server invocations without cluttering the update logic. There is a place where I can read more for reasons?

**Comment by bender2k14** [comment]
Quoting part of deleted comment by @MecuSorin.
> Why is removed? For my project will be a bad thing, is a very nice commodity to reduce the server invocations without cluttering the update logic. There is a place where I can read more for reasons?

These are good questions.  I assume you deleted your comment because you found the reason.  For anyone else following along, read the first bullet point in https://github.com/elmish/Elmish.WPF/issues/253#issue-674282832.

> I see that you are using the `wrapDispatch` parameter. Note that this parameter is [being removed in v4](https://github.com/elmish/Elmish.WPF/issues/253). Let us know in that issue if that will cause problems for you.

Oh, I didn't notice that.  Thanks for pointing this out.  I now see the `wrapDispatch` argument is supplied the functions `debounceMessage 200` and `debounceMessage 150`.

Quoting myself in https://github.com/elmish/Elmish.WPF/pull/244#issuecomment-669461630
> You mean the throttling, debouncing, and limiting features, right? My hope is that we can delay this work. If no one is using the `wrapDispatch` feature, then we don't even need to provide a partial migration path (right away).

One person is enough for me.  I will implement throttling, debouncing, and limiting for v4.

@MecuSorin, do you mind sharing your implementation of `debounce`?  I am interested to see how did it.

**Comment by cmeeren** [comment]
> One person is enough for me. I will implement throttling, debouncing, and limiting for v4.

I'd suggest waiting for reply. While it is used, it may be that it is not actually needed. For example, in your original slider example, I think we found out that WPF "debounces" the events itself. At least I think that's what I experienced; quickly moving a slider back and forth between 0 and 1000 did not cause thousands of messages.

**Comment by cmeeren** [comment]
Quoting the same part of the deleted comment by @MecuSorin:

> Why is removed? For my project will be a bad thing, is a very nice commodity to reduce the server invocations without cluttering the update logic. There is a place where I can read more for reasons?

The debounce is intended for the "WPF side" only, because it is the only way to achieve that. If you have server calls as a direct result of the messages, you can add debounce logic to the server calls in the code that calls the server (again without cluttering `update` - just return the commands you otherwise do).

**Comment by cmeeren** [comment]
@bender2k14 In conclusion, unless I have misunderstood @MecuSorin's point/usage, I still think we're fine not adding debounce etc., since the usage doesn't require debouncing the actual dispatches (and may indeed benefit from dispatching at a lower level).

**Comment by bender2k14** [comment]
All good points @cmeeren.  I will leave issue #271 open for now but not work on it yet.

**Comment by MecuSorin** [comment]
I deleted my reply because I wasn't notice the link that @cmeeren provided.

@bender2k14 The implementation is actual a **sample**, but used the term **debounce** because will be easier for my colleague to understand the concept:
```
let asDispatchWrapper
            (configure: IObservable<'msg> -> IObservable<'msg>)
            (dispatch: Dispatch<'msg>)
            : Dispatch<'msg> =
    let subject = Subject.broadcast
    subject |> configure |> Observable.add dispatch
    fun msg -> async { return subject.OnNext msg } |> Async.Start
let inline debounceMessage (millis: int) =
    Observable.sample (TimeSpan.FromMilliseconds (float millis)) |> asDispatchWrapper
```

I was thinking that if is hard to implement on this end, maybe we can play with the other end and decorate the update function with something that will have this behavior.
Launching another idea: or instead of using the dispatcher at it is, maybe we can provide, from bindings, some Observables, and somewhere in the loop, the dispatcher task will be to switch (combine) all the Observables

**Comment by cmeeren** [comment]
@MecuSorin,

Thanks for the suggestions. I am hesitant to do something as disruptive as changing the fundamental way the bindings work. Also, I can't see what utility there would be in doing this, nor in decorating the `update` function (which sounds like a bad idea since that makes this otherwise pure function less deterministic/understandable).

I currently stand by my suggestion of placing the debouncing/sampling/throttling of server calls in the actual server call code.

**Comment by MecuSorin** [comment]
@cmeeren 
Maybe in your domain you can cut the calls there, but in my domain, every call to the server have a state change so I cannot go out of sync like that. The thing is that the contract is quite complex and big, so having the extra indirection in the update function is not a pretty perspective. This is why I was liking very much the granularity at the bindings level.

**Comment by bender2k14** [comment]
It sounds to me like you are putting domain logic in your WPF bindings.  I would expect that you want the debouncing of server calls to exist even if you replaced your WPF GUI with a CLI.

> The thing is that the contract is quite complex and big, so having the extra indirection in the update function is not a pretty perspective.

If you share a branch that includes the deboucing in your location of choice (in a binding as in the code above or as an extra indirection in the update function), then I will review it.  Maybe I can find a solution with "all of the advantages" and "none of the disadvantages".

To simulate server calls, maybe your branch could ping `127.0.0.1`.

**Comment by cmeeren** [comment]
> It sounds to me like you are putting domain logic in your WPF bindings. I would expect that you want the debouncing of server calls to exist even if you replaced your WPF GUI with a CLI.

Yes, I agree. If I had to to sync server calls with state change in a way that meant I could not place the debouncing "below" the `update` in the HTTP client code, then I would likely just place the necessary state for debouncing in the model, and use update and commands to do debouncing. That way it could also be unit tested, since everything is pure.

I get that the current `wrapDispatch` is a nice way to work around this issue, but it was only ever meant to reduce the amount of triggers from WPF, not do anything related to domain code or other infrastructure.

In any case, these are just my two cents. if you share a branch as described by @bender2k14, then I'm sure we can resolve this in a way that works well.

**Comment by MecuSorin** [comment]
I would love to share the code, but is not possible. 
Point taken about the domain logic and I agree with it. This doesn't invalidate the common usage of the UI singals|events|triggers that can be less noisy with a mechanism like the ```wrapDispatch```.

**Comment by cmeeren** [comment]
> This doesn't invalidate the common usage of the UI singals|events|triggers that can be less noisy with a mechanism like the `wrapDispatch`.

You are right, but our experience so far has been that it has never actually been needed, and no users have come forth yet with a compelling case where the feature is actually needed and solves a problem that can't be reasonably solved another way.

**Comment by bender2k14** [comment]
> I would love to share the code, but is not possible.

Yes.  I certainly understand that you can't share your actual code.  However, could you create a minimal working example that is representative of your private code?
