### ISSUE TITLE
Visual Studio 2019 allways create .Net 5 project how to can I change it to create net core 3 at start up

### ISSUE THREAD

**Issue by stevensrf11** [elmish/Elmish.WPF#276]
Any .Net core project I create in VS 2019 creates the project as .Net 5. 
In a WPF application the MaindowWindow in XAML can not be viewed in the designer.
I get some gd System.InvalidOperationException BS

If change the project's to .Net Core 3.0 this does not fix that problem.
What do I need to do so any core project is create at a Net Core 3 or 3.1 instead of 5 when first created.

**Comment by bender2k14** [comment]
.NET 5 is still in preview.  My guess is that you are also using a preview version of Visual Studio.  I do not recommend that.

You can check if your issue is known [here](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-known-issues.md) or by searching the issues [here](https://github.com/dotnet/core/issues).  If you don't find anything, then you create an issue [here](https://github.com/dotnet/core/issues/new).

**Comment by stevensrf11** [comment]
Your guess is completely wrong

I am using Visual Studio 2019 .

Microsoft Visual Studio Enterprise 2019
Version 16.7.1

 

 
 

Sent: Thursday, September 10, 2020 at 12:11 PM

**Comment by stevensrf11** [comment]
That its closed an issue on something you are complete wrong about

**Comment by bender2k14** [comment]
I didn't close this issue because of an assumption.  I closed it because it doesn't have anything to do with Elmish.WPF.

If you are having trouble with Elmish.WPF, then I can help you.

However, it seems to me like you are having a problem creating a project with Visual Studio that involves .NET 5, which does not yet have a stable version.  I know almost nothing about .NET 5.  If you want help with Visual Studio and .NET 5, then you should create an issue [here](https://github.com/dotnet/core/issues/new).
