### ISSUE TITLE
Design Question -- How best to modify multiple child lists in a DataGrid

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#291]
This goes to understanding.

Being new to Elmish.wpf and F#, I'm still trying to get a get grasp on the order in which messages, bindings, and updates occur when a user makes a selection from the WPF/Xaml. As a learning experiment, I have a DataGrid that is broken down into Rows, which are then divided into Columns. The Columns are further broken down into a list of cells. Hence, the datagrid consists of 10 rows, each row has 4 columns, each Column has 4 Cells. ( So, I have 40 cell lists)

Two questions:

1.  The user selects a cell directly from the user interface (WPF/C#).  If I am reading this correctly, Elmish.WPF immediately acts on the binding for the selected cell, then moves upward to notify the Column which that cell is in, which in turn goes upward to notify the Row holding that Column--- is this correct?  

2.  With the above setup of a list of Rows, to a list of Columns, to a list of Cells, the current design is allowing cells to be selected only uniquely to each cell list. Hence, cells can be chosen from multiple lists (not what I want). So what would be the best approach of "clearing" or "deselecting" the last cell selected when it is in a different list from the currently selected cell?  That is ultimately, only one cell in the DataGrid can be active at any one time.

(My thinking is circular, I keep wondering if raising an event in the WPF/xaml upon cell selection may not be the most efficient way to handle this? or somehow passing a delegate from the higher level rows to a "reset" method in each cell to clear non-selected cells? or something else? ).

Thanks for any and all suggestions.

**Comment by TysonMN** [comment]
> 1. The user selects a cell directly from the user interface (WPF/C#). If I am reading this correctly, Elmish.WPF immediately acts on the binding for the selected cell, then moves upward to notify the Column which that cell is in, which in turn goes upward to notify the Row holding that Column--- is this correct?

I think this makes it sound like Elmish.WPF is the first mover.  It is not.  WPF is still in charge.  For a given user action, the types and order of events in WPF are raised (or not) in either the default order or some other order if you did something in the XAML/C# to change the order, suppress some event, and add some event.

Elmish.WPF receives the flow of control on the UI thread from WPF to handle some event.  It uses this flow of control on the UI thread to update the model and being the execution of any commands.  Then flow of control returns to WPF to raise the next event.  In this way, every event raised by WPF is handled in sequence.  This is a key aspect of the Elm architecture.  It completely removes race conditions from the application (other than those explicitly put into commands).

> 2. With the above setup of a list of Rows, to a list of Columns, to a list of Cells, the current design is allowing cells to be selected only uniquely to each cell list. Hence, cells can be chosen from multiple lists (not what I want). So what would be the best approach of "clearing" or "deselecting" the last cell selected when it is in a different list from the currently selected cell? That is ultimately, only one cell in the DataGrid can be active at any one time.

You need to handle the selection event for a certain list of cells by not only selecting the cell in that list but also deselecting in all the other lists of cells.  You want an interaction in one child to effect the state of another child.  This is hard to do in any architecture.

I can help you more with this if you share your code.

> I keep wondering if raising an event in the WPF/xaml upon cell selection may not be the most efficient way to handle this?

Sometimes a problem can be solved in the code-behind.  However, this is not recommended even when not using Elmish.WPF.  The requirement that at most one cell is selected is not just a visual aspect but a fundamental requirement of your application: it is a business rule.  As such, you should solve this in your model and logic instead of in the view.

**Comment by awaynemd** [comment]
@TysonMN Hard is an understatement. In C#, I resorted to the event aggregator pattern. Not the best, but it worked. I think it can be better done with F#.

My starting point is at:  https://github.com/awaynemd/DataGridWithButtonReset

The button reset was just to see if I could do it!  The plan was to  integrate a "reset" to all cells before having the selected cell be set. Didn't work :(

Thanks for your help!

**Comment by TysonMN** [comment]
The code in [this PR](https://github.com/awaynemd/DataGridWithButtonReset/pull/1) achieves the desired behavior.

**Comment by awaynemd** [comment]
@TysonMN Thank you very much! As an aside, how does one review a PR before merging it? Thanks again.

**Comment by TysonMN** [comment]
You're welcome.

I am not completely sure what GitHub means by a PR review.  In practice though, you can make a comment on the PR as a whole or you can make a comment on a line or lines in the file view.
