### ISSUE TITLE
How to implement delays between messages?

### ISSUE THREAD

**Issue by xperiandri** [elmish/Elmish.WPF#294]
I want to achieve a 1 second delay between messages
``` F#
let launched greating introduction askForPhone = Cmd.batch <| seq {
    BotMessage greating |> Cmd.ofMsg
    Async.Sleep 1000 |> Cmd.OfAsync.start
    BotMessage introduction |> Cmd.ofMsg
    Async.Sleep 1000 |> Cmd.OfAsync.start
    BotMessage askForPhone |> Cmd.ofMsg
}
```
What is the correct implementation?

**Comment by TysonMN** [comment]
As you imply, all five of those commands execute at the same time (...really, [each is independently started](https://github.com/elmish/elmish/blob/87fb741fdbecbfd58ece6e171d376afcd8de62ee/src/cmd.fs#L136-L140) without wanting for the previous ones to finish and [execution eventually starts here](https://github.com/elmish/elmish/blob/87fb741fdbecbfd58ece6e171d376afcd8de62ee/src/cmd.fs#L26)).

You need to do something more like this code in the `SubModel` sample.
https://github.com/elmish/Elmish.WPF/blob/d91c4790a3f57e2f87a6bfee57b29a2d1ce2f0ac/src/Samples/SubModel/Program.fs#L138-L148

If you provide a GitHub repository containing those commands executing at the same time, that I can probably give you a more specific answer.

P.S.
This issue is more appropriate for [Elmish](https://github.com/elmish/elmish).

**Comment by xperiandri** [comment]
https://zaid-ajaj.github.io/the-elmish-book/#/chapters/commands/async-updates
``` F#
let launched greating introduction askForPhone (dispatch : Dispatch<Msg>) = Async.StartImmediate <| async {
    do dispatch <| BotMessage greating
    do! Async.Sleep 1000
    do dispatch <| BotMessage introduction
    do! Async.Sleep 1000
    do dispatch <| BotMessage askForPhone
}
```

``` F#
Cmd.ofSub (Dialog.launched strings.[Strings.Greating] strings.[Strings.Introduction] strings.[Strings.AskForPhone])
```
