### ISSUE TITLE
Is it possible to observe elmish update from code-behind?

### ISSUE THREAD

**Issue by Evangelink** [elmish/Elmish.WPF#296]
I am using an external library that provides "WPF" components but some properties are not bindable. Previously, I was using ReactiveUI and so it was possible for me to observe/react to a viewmodel property change in the view code-behind to actually manually set the properties I need. 

I am wondering if there is any way to somehow observe the messages from the view code-behind?

If it's not possible I think I could either manually create some dependency properties on my view code-behind and bind these to the view model OR to actually have the viewmodel exposing through some property an instance of the UI object, so that I can set the properties in the update.

In case it's not possible, do you have any recommendation toward which technique would fit best the elmish model?

**Comment by TysonMN** [comment]
> ...think I could either manually create some dependency properties on my view code-behind and bind these to the view model...

I think you could too, and I think this is the best solution.

> ...I think I could...actually have the viewmodel exposing through some property an instance of the UI object, so that I can set the properties in the update.

I am not exactly sure what you mean here.  If you mean that your `update` function would mutate the UI object, then I do not recommend this.  Your `update` function should be pure.  Alternatively, if you mean your `update` function would return a `Cmd` that executes a function that mutates the UI object, then this is acceptable.  I am doing this in two places in my application at work.

In the first, I am using [SKElement](https://docs.microsoft.com/en-us/dotnet/api/skiasharp.views.wpf.skelement) from [SkiaSharp](https://github.com/mono/SkiaSharp).  To redraw the screen, I need to execute [UIElement.InvalidateVisual](https://docs.microsoft.com/en-us/dotnet/api/system.windows.uielement.invalidatevisual).  In the second, I am using the snackbar from [Material Design in XAML](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit).  Enqueuing a message to the snackbar is achieved through one of [these functions](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/f05c5f12424084a2982b398385d60eba391f7375/MaterialDesignThemes.Wpf/ISnackbarMessageQueue.cs).

My C# project is the startup / entry-point project.  I pass the two functions to the F# code via a class (since the F# to C# interop is good in that case).  Then I pass those two functions as arguments in the functions that map command message (`CmdMsg`) to a command (`Cmd`) since I am using the [command message pattern](https://github.com/elmish/Elmish.WPF#how-can-i-test-commands-what-is-the-cmdmsg-pattern).

> ...is any way to somehow observe the messages from the view code-behind?

As an absolute last resort, you could cast your viewmodel (which is an instance of `Elmish.ViewMdoel<,>`, a type that you can't see at compile time because its scope is private) to [`DynamicObject`](https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.dynamicobject).  I think this is the interface that WPF utilizes.  In particular, it should be possible to subscribe to property change notifications, but I have never tried any of this.

However, I do not recommend this.

P.S.
You are asking about how to change the UI because of a previously dispatched message.  If instead you want to dispatch a message based on some UI change, then check out the [`EventBindingsAndBehaviors` sample](https://github.com/elmish/Elmish.WPF/blob/master/src/Samples/EventBindingsAndBehaviors.Views/MainWindow.xaml), which converts an event into a command.  Then a message can be dispatched via a `Cmd` binding.

**Comment by cmeeren** [comment]
> However, I do not recommend this.

No, definitely not. Then you are depending on implementation details which may change at any time.

**Comment by TysonMN** [comment]
Great point.  I would have used this to debug something recently (but I didn't think of this possibility at the time), but I would never use this approach in an application.

**Comment by Evangelink** [comment]
Thank you for the fast feedback!

I have used the event to command for the UI part and I have used the subscription pattern for events on non-UI third parties. It seems to be all good for now.
