### ISSUE TITLE
Docs point to samples in master, which doesn't necessarily compile using latest version from NuGet

### ISSUE THREAD

**Issue by BentTranberg** [elmish/Elmish.WPF#329]
Background : I made a mistake, that even caused me to report an issue (#327), thinking that sample Validation/Validation.Core from master would work with the latest NuGet version. Had to think a little before realizing what I did wrong.

Problem : **The documentation main page actually links to the samples in master, and not in the latest tag. This has even greater potential to cause trouble for users, especially users that aren't even aware of how version control systems work when they run into this.**

So I suggest the docs should link to the samples in "latest tag".

I don't know if there is a mechanism that allows docs to link to samples in "latest tag" rather than master. If there isn't, can a tool in a build maintain this? Not ideal to have to maintain this sort of thing manually.

edit/append: After looking around a bit here, I can see I'm slightly off in my use of terms. But you get my meaning anyway. I don't use Git and GitHub in my business.

**Comment by cmeeren** [comment]
I know what you mean.

What changed in `master` that is not compatible with current NuGet? Have we made breaking changes to `master`? That's not good. We have a `v4` branch for breaking changes.

Unfortunately I don't have the capacity to look into this for the time being. @TysonMN, are you able to investigate?

**Comment by BentTranberg** [comment]
In that case I shouldn't have closed #327, and I shouldn't have made this issue report either. I'm reopening the other, and leave it up to you guys to close these whenever.

**Comment by cmeeren** [comment]
Personally I think it makes sense to leave #327 closed and this one open, but I'll have to drop this ball now.

**Comment by TysonMN** [comment]
I added a feature.  That feature was support for lists of validation errors.  The validation sample in `master` uses this feature.  We have not made a release since I added that feature, so the validation sample does not compile with the most recently released NuGet package.  We could go a minor release now.  Then the samples in `master` would compile with the most recently released NuGet package.

**Comment by cmeeren** [comment]
That's good to hear. I suggest we release this. Are you able to do that?

**Comment by TysonMN** [comment]
I pushed commit https://github.com/elmish/Elmish.WPF/commit/04dc145cdd2923c7625338a440f886261c927341 but [the automated build didn't publish the NuGet package](https://ci.appveyor.com/project/cmeeren/elmish-wpf#L122).  What did I do wrong?

I think I would like to change the DevOps here to what is used in fsharp-hedgehog and fsharp-hedgehog-experimental, which uses a GitHub Action instead of AppVeyor.

**Comment by cmeeren** [comment]
See the [deployment checklist here](https://github.com/elmish/Elmish.WPF/blob/master/.github/CONTRIBUTING.md#deployment-checklist). You have to create and push a tag. The commit looks fine. 👍 Thanks!

> I think I would like to change the DevOps here to what is used in fsharp-hedgehog and fsharp-hedgehog-experimental, which uses a GitHub Action instead of AppVeyor.

I think the "increment version and push tag" is more or less as simple as it gets, but if you think changing to GitHub Actions brings some benefits, knock yourself out. I haven't had a chance to delve into it myself.

**Comment by TysonMN** [comment]
That worked.  Thanks for the reminder @cmeeren.

@BentTranberg, version 3.5.7 now available!

**Comment by TysonMN** [comment]
Oh.  I meant to set the version to 3.6.0 since we added to the API.

Does anyone care?

**Comment by cmeeren** [comment]
I'm comfortable with letting it slide.
