### ISSUE TITLE
How close window by subModel msg

### ISSUE THREAD

**Issue by eu-genes** [elmish/Elmish.WPF#382]
Hi, trying pass data from SubModel ( subModel for ModalWindow) to Main, my models update funcs like:
source: [https://github.com/eu-genes/elmishclosewindow](https://github.com/eu-genes/elmishclosewindow)
```f#
(*Main -> ModalWin  -> SubModel*)
module SubModel =
  let update msg m =
    match msg with
       | RandomId -> { m with Id = System.Random().Next(1, 1000)}
 
  "Random" |> Binding.cmd RandomId

module ModalWin =
  let update msg m =
    match msg with
      | SubMsg (SubModel.RandomId) -> 
        {m with Id = m.Sub.Id; Sub = SubModel.update (SubModel.RandomId) m.Sub}

module Main =
  let update msg m =
    match msg with
      | WinMsg msg' -> 
        match m.Win with
          | Some m' -> 
            if m'.Id > 0 then {m with Id = m'.Id; Win = None} 
            else {m with Win = Some <| ModalWin.update msg' m'} 
          | None -> m
```
Should work like this: once call Random cmd, gen new random value, close window, Main model gets value.
But now Random cmd call three times before window was closed. How to fix it?

**Comment by TysonMN** [comment]
> Should work like this: once call Random cmd, gen new random value, close window, Main model gets value.
> But now Random cmd call three times before window was closed. How to fix it?

I think you were confusing yourself.  You have two views / Windows but three model types and each of them as a field called `Id`.  As you said, it was taking three clicks total to achieve your desired behavior.  That is two extra clicks.  One of those clicks is because the predicate was written against `ModalWin.Model.Id` instead of `SubModel.Model.Id`.  The other extra click was because you were inspecting the value of that field before calling `ModalWin.update`.

I just created PR https://github.com/eu-genes/elmishclosewindow/pull/1 that achieves your desired behavior by fixing both of those problems.  Before that commit that made that change, I made several commits that clean up the code.

**Comment by eu-genes** [comment]
Thank you so much for your help! You did a great job in your commits.
> One of those clicks is because the predicate was written against `ModalWin.Model.Id` instead of `SubModel.Model.Id`.

my fail, i have missed it

> The other extra click was because you were inspecting the value of that field before calling `ModalWin.update`.

yes, this is the real reason for my issue, thanks

**Comment by TysonMN** [comment]
And thanks so much for the subscription! :D

**Comment by eu-genes** [comment]
```f#
let m'' = ModalWin.update msg' m'
```
Such "forced calling update", is good practice?

**Comment by TysonMN** [comment]
It is fine. Each `update` function should be pure, so it is safe to call. There are probably clearer ways to express this, but it doesn't matter for the MWE you shared with this issue though.
