### ISSUE TITLE
Using DataTemplateSelector to choose ContentControl

### ISSUE THREAD

**Issue by PaulSmithTrick14** [elmish/Elmish.WPF#391]
I am experimenting with using a DataTemplateSelector to determine which UserControl is shown in a ContentControl.  I have a project at [ElmishDataSelector](https://github.com/PaulSmithTrick14/ElmishDataSelector) (pretty new to this, hope everything is included)

The basic idea is that MainWindow has some GlobalState and some variable state.  The variable state is a Discriminated union CurrentPane: Pane.Model

The XAML should show a different control depending on the type of the variable state.  At the moment there are only two possibilities an InputGatherer and a ReportViewer.  If Pane.init() sets Specific to be GatherInput then an InputControl is displayed.  If Pane.init() sets Specific to be ShowReport then the ReportViewer is shown.  All good.

But I want to click on the buttons to change the pane that is current.  Looking at the log I can see that the Model does change but there is no PropertyChanged raised for the "Pane" subModel binding.  PropertyChanged is raised for "PaneType" but both bindings should have changed.

What am I doing wrong?  Or, does someone have an example of using a DataTemplateSelector with Elmish.WPF

**Comment by TysonMN** [comment]
> [...] Model does change but there is no PropertyChanged raised for the "Pane" subModel binding. PropertyChanged is raised for "PaneType" but both bindings should have changed.

A `SubModel` binding can be created via overloaded methods named `SubModel` or `SubModelOpt`.  When created via `SubModel` ([as you are doing](https://github.com/PaulSmithTrick14/ElmishDataSelector/blob/c5dcdf469ccecc7595663da3b7762515eae5d15a/Samples/TemplateSelector.Core/Program.fs#L142)), [the `PropertyChanged` event for such a binding is never raised](https://github.com/elmish/Elmish.WPF/blob/21c98b43700bfc5a1e3d71a755b461be6cddcdbb/src/Elmish.WPF/ViewModel.fs#L366-L368).  This is the intended behavior.  Elmish.WPF created a `ViewModel<_,_>` instance for your model, and the reference it gave to WPF has not changed.

> What am I doing wrong? Or, does someone have an example of using a DataTemplateSelector with Elmish.WPF

In my application at work, I show one screen or another by creating two `SubModel` bindings and then using the value of a discriminated union to show the correct one via bindings to [`Visibility`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.uielement.visibility).

However, I wouldn't say that the way I am doing it is right or that the way you are trying to do it is wrong.  I don't consider myself an expert on WPF specifically, so maybe there is a better way to solve this problem than I am currently.

If you share another example program that achieves your desired behavior and does not use Elmish.WPF, then I will submit a pull request to your above repo that achieves your desired behavior and uses Elmish.WPF.

**Comment by PaulSmithTrick14** [comment]
[This is a purely C# example of using a DataTemplateSelector](https://github.com/PaulSmithTrick14/TemplateSelectorCS) that shows what I am trying to achieve.

Thanks for your help

**Comment by TysonMN** [comment]
Instead of switching the template based on the type of the view model, this branch and corresponding PR switches the template based on the name of your backing model.  In F#, I would expect this name to be [the cases in this discriminated union](https://github.com/PaulSmithTrick14/ElmishDataSelector/blob/96172d7a2e3b821b39d8ad3bf015cb435a94f93e/Samples/TemplateSelector.Core/Program.fs#L58-L60).

Do you understand how you can make that approach work with Elmish.WPF?

I am not sure how I feel about this approach.  My current institution is that two `SubModel` bindings created via overloads of `Binding.subModelOpt` and show or hidden because of `Visibility` bindings would be better, but maybe my intuition is wrong.

Do you know of any performance (in time or space) considerations that suggests one of these approaches is better than the other?

**Comment by PaulSmithTrick14** [comment]
Thanks for your help.
