### ISSUE TITLE
[Bug?] Change of behavior in Elmish.WPF beta compared to release

### ISSUE THREAD

**Issue by Evangelink** [elmish/Elmish.WPF#403]
Hi there,

In my app, I have implemented a way to ask for user to save, discard or cancel on unsaved changes while exiting the application.

I have noticed a change of behavior/bug in Elmish.WPF beta compared to latest release version.

I have created a reproducer (that is partially mimicking the real app) that you can find here https://github.com/Evangelink/Elmish.Wpf.Experiments/pull/7. Note that I have included the telerik dlls for you to test.

**Comment by TysonMN** [comment]
The difference in behavior is intentional.  The change was made in PR #374.  Before, all messages were dispatched synchronously.  The new behavior is to dispatch UI messages synchronously and all other messages (i.e. those from commands or subscriptions) asynchronously.

Your use case required synchronous dispatching, which is why you saw the different / worse behavior.

However, you can adjust your implementation to dispatch through the UI so that it is synchronous once again.  See PR https://github.com/Evangelink/Elmish.Wpf.Experiments/pull/8.

**Comment by Evangelink** [comment]
As always, thank you for the precious tips and quick answer.

**Comment by Evangelink** [comment]
@TysonMN Is it possible to force one `CmdMsg` to be now processed synchronously?

**Comment by TysonMN** [comment]
That is a really good question.  Defaulting to asynchronous Cmd / subscription dispatch but opting-in to synchronous Cmd dispatch would still compatible with the previous reason I changed this behavior.

I created issue #407 to track this question.
