### ISSUE TITLE
Remove deprecation for Binding.subModelOpt until a replacement exists

### ISSUE THREAD

**Issue by cmeeren** [elmish/Elmish.WPF#448]
`Binding.subModelOpt`  is marked as obsolete. To silence the warning, the message instructs to wait for v5 (based on the NuGet history, we're still at v4 beta and not much is happening), or to use the method implementation (which I don't really think is a good idea just to silence a deprecation warning). Alternatively I can (presumably) disable warnings for obsolete code altogether for my project, which I don't want.

I suggest that code not be marked as obsolete before there is a suitable replacement to nudge the users towards.

**Comment by TysonMN** [comment]
Sure. The issue is that I want to keep the name but change the signature. So the migration process is to switch to something else for v4 and then switch back to this for v5. 

I will review the specific details this weekend and then comment here again.

**Comment by TysonMN** [comment]
> we're still at v4 beta and not much is happening

Yes, sorry about that.  I have not had much time available for Elmish.WPF lately.  I still intend to complete all this work though.

> `Binding.subModelOpt` is marked as obsolete.

There are six overloads of the method `Bindings.subModelOpt`.  I assume you mean one of the two overloads with this `Obsolete` message:

https://github.com/elmish/Elmish.WPF/blob/e9d9fbac5c8279f2bae126635479ff33d700ae62/src/Elmish.WPF/Binding.fs#L2629-L2630

> Alternatively I can (presumably) disable warnings for obsolete code altogether for my project, which I don't want.

I don't want you to do that either.

> To silence the warning, the message instructs to wait for v5 (based on the NuGet history, we're still at v4 beta and not much is happening), or to use the method implementation (which I don't really think is a good idea just to silence a deprecation warning).

My goal with this obsolete message is to provide a migration path that doesn't involve fixing a compiler error.  I think replacing this method call with (presumably a specialization of) its implementation its a good idea.  First, I think it is likely that the method signature is forcing calling code to be more complicated than it needs to be.  (That is why I am going to simply its signature in a future version.)  Second, the easiest way to replace a call to this method with its implementation is to copy this method into your code and replace calls to this method with calls to your local copy of this method.

Do you have another idea for how to provide users with a migration path that does not introduce a compiler error with incrementing the major version (except from the removal of code marked obsolete)?

**Comment by cmeeren** [comment]
> Do you have another idea for how to provide users with a migration path that does not introduce a compiler error with incrementing the major version (except from the removal of code marked obsolete)?

No, though I don't find that to be an important goal in my own OSS projects, and it's not something I miss in projects I consume. Whenever I update a dependency to a new major version, I have to check the changelog anyway, because there may be breaking behavioral changes that do not cause compiler errors. (I prefer that all breaking changes cause compiler errors, but sometimes it's not practical, and you never know how other people think, so I must always check.) I expect the changelog to document all breaking changes as well as clear migration paths.

Of course, all else being equal, I appreciate as smooth a transition as possible. I expect that is your goal by marking the method as obsolete and instructing to replace the call with a call to a local copy of the same implementation. But that causes extra pain right now, so all else is not equal in this case. Personally, I would rather not face compiler errors (or warnings, which I elevate to errors) unless there is already in place a clear migration path. I would rather face breaking changes in a major version (as long as they are well-documented with a clear migration path, which they need to be anyway).

Note that I may of course be missing some important context as to what exactly the changes are.

Also note that I am writing this as a consumer of Elmish.WPF, not as a previous maintainer. You're the boss. 🙂

**Comment by TysonMN** [comment]
I don't think you are missing anything.

It is reasonable to introduce a compiler error in a new major version and explain the migration path in the change log.  I think I will also do this.  However, I also like my current approach of giving the user instructions right were they would experience the compiler error instead of having to figure out if the change log impacts them.

Can you share your call to this method?  I expect replacing it with its implementation and then simplify would lead to a satisfactory result.

**Comment by cmeeren** [comment]
> Can you share your call to this method?

```f#
  "Login"
  |> Binding.subModelOpt (
      (function
      | Login m -> Some m
      | _ -> None),
      snd,
      LoginMsg,
      loginBindings
  )
```

> However, I also like my current approach of giving the user instructions right were they would experience the compiler error instead of having to figure out if the change log impacts them.

Ideally, they figure out if a breaking change affects them by getting a compiler error.

Another drawback: If I replace it with the method implementation as suggested, I will get no warning or other notification when an "official" replacement is finally available. If I want to use the new alternative, I will have to check all changelogs and try to understand them well enough to determine when a suitable alternative is added. This is a lot more work than just fixing a compiler error (particularly if the compiler error is due to `ObsoleteAttribute` and contains a helpful message).

---

An alternative is to use another name for the new APIs in v5. That would remove the need for this "dance" of deprecation and planned renames.

**Comment by TysonMN** [comment]
> Another drawback: If I replace it with the method implementation as suggested, I will get no warning or other notification when an "official" replacement is finally available. If I want to use the new alternative, I will have to check all changelogs and try to understand them well enough to determine when a suitable alternative is added.

I think it is reasonable to keep the simplified implementation.  In your case, I think that would be
```fsharp
"Login"
|> Binding.SubModel.opt loginBindings
|> Binding.mapModel (function Login m -> Some m | _ -> None)
|> Binding.mapMsg LoginMsg
```

To put them next to each other, this is your current code
```fsharp
"Login"
  |> Binding.subModelOpt (
    (function
    | Login m -> Some m
    | _ -> None),
    snd,
    LoginMsg,
    loginBindings
)
```

The simplified implementation is fewer lines, and I think it is more readable.

Which do you prefer?

--------

> An alternative is to use another name for the new APIs in v5. That would remove the need for this "dance" of deprecation and planned renames.

Yes.  However, I think the current name is the best, so I want to "reuse" that name for the new function.

**Comment by cmeeren** [comment]
> Which do you prefer?

Just by looking at it, I prefer the former (the "implementation" in this discussion). I haven't investigated the `Binding` module API; it's new to me. I didn't realize it looked that good/composable. Is that API intended to be used publicly going forward? What is the reason for actively maintaining (through deprecations, modified implementations, etc.) the method-based API?

**Comment by TysonMN** [comment]
> I prefer the former (the "implementation" in this discussion).

I am glad you like it :)

> Is that [function-based binding] API intended to be used publicly going forward?

Absolutely!

> What is the reason for actively maintaining (through deprecations, modified implementations, etc.) the method-based API?

I thought about advantages (and disadvantages) of both a function-based API and a method-based API.  Here is what I concluded:

Function-based API advantages:
- idiomatic for F#
- usually more readable...because each argument is provided one at a time (c.f. fluent interface or builder pattern)
- efficiently expresses alternatives by calling or not calling individual functions
- more helpful/informative compiler errors when called incorrectly

Method-based API advantages:
- often allows for more terse code
  - the simplest cases of multiple function calls can be combined into a single method call with multiple arguments while remaining readable
  - efficiently expresses alternatives via overloads when there are multiple ways the express the same concept (such as `Option` vs `ValueOption`)

I also think of the following being an advantage for methods:
- often allows for more terse code
  - common groupings of function calls can be combined into a single method with a higher-level name

However, I could also define a function that accepts two or more arguments (technically the binding and then two or more additional arguments), but as a stylistic choice to have a more consistent and predictable API, I only want functions in the function-based binding API to accept one arguments (technically the binding and then one additional arguement).

**Comment by cmeeren** [comment]
I see. Feel free to close this issue. 🙂
