### ISSUE TITLE
Need a GetParentNode function for RoseTree

### ISSUE THREAD

**Issue by ScottHutchinson** [elmish/Elmish.WPF#527]
For the RoseTree at [https://github.com/elmish/Elmish.WPF/blob/master/src/Samples/SubModelSeq.Core/Program.fs#L128](https://github.com/elmish/Elmish.WPF/blob/master/src/Samples/SubModelSeq.Core/Program.fs#L128), I need to traverse all the ancestors of a particular node. This is analogous to getting the path to a file. If I had a GetParentNode function like the one defined in Haskell in the below link, then I should be able to iteratively get all the ancestors. I will try to port this Haskell function, since I haven't found anything similar in F#, but since I don't know how to read Haskell, I meant need some help.

[https://stackoverflow.com/a/68018282/5652483](https://stackoverflow.com/a/68018282/5652483)

**Comment by LyndonGingerich** [comment]
I don't know Haskell, either. Is there a Haskell help forum or Slack channel somewhere, perhaps?

**Comment by ScottHutchinson** [comment]
I just posted a cry for help at [https://fsharp.slack.com/archives/C1R50TKEU/p1665157751425439](https://fsharp.slack.com/archives/C1R50TKEU/p1665157751425439).

**Comment by TysonMN** [comment]
What are you actually trying to do?

C.f. https://en.wikipedia.org/wiki/XY_problem

**Comment by TysonMN** [comment]
In MVU, I think the correct way for a child to "communicate" with is parent is by using an out message.

Can you share a branch where clicking `Select All` selects the one parent and its children?

Then I will modify it to also select all the ancestors.

**Comment by ScottHutchinson** [comment]
@TysonMN , working on it.

**Comment by ScottHutchinson** [comment]
@TysonMN , The last commit on [this branch](https://github.com/ScottHutchinson/Elmish.WPF) adds the code to select and clear the right-clicked parent and all its children and grandchildren, etc.. In this sample, select means increment the counter and clear means decrement the counter. In my application it will mean setting a boolean property (and checking the bound checkbox).

To see it working, run the SubModelSeq sample, add some children and/or grandchildren, then right-click on a parent and choose Select All or Clear All to see the counters increment or decrement.

**Comment by TysonMN** [comment]
Great. I will look at this tonight.

**Comment by TysonMN** [comment]
You didn't link to a branch, and I don't see any branches in your fork of Elmish.WPF.

**Comment by ScottHutchinson** [comment]
I was a bad boy and modified the master branch.

**Comment by ScottHutchinson** [comment]
https://github.com/ScottHutchinson/Elmish.WPF/commit/b3de5b74b17fe1e7bb68bd5908763601916c79a9

**Comment by TysonMN** [comment]
Part 1 of 2: Cleaning up your code

See commit https://github.com/TysonMN/Elmish.WPF/commit/317db56059617d1e9d979fcf4288dc07b1ab29fc.

I replaced the function you called `traverse` with `RoseTree.map`.  This function is the `map` function of the [functor](https://blog.ploeh.dk/2018/03/22/functors/) `RoseTree<'a>`.  There is another concept called a [traversable](https://fsharpforfunandprofit.com/posts/elevated-world-4/) that has a function called `traverse`, so it is best to only use that name for a function when you are implementing that function for a traversable.

I greatly simplified your implementation of `setCounterForAll`.  I can see now way you thought it was a great burden that I added the `IsOpen` field in its own record.  Yes, if you write code like you did, then I agree that having to deal with another type is a great burden.  On the other hand, if you write code like I just did, then the addition of this record is trivial.  If this code had existed before I added that record, then the change to this function would have been to add `|> Openable.Value.map` on its own line (so the diff could not be more readable).

**Comment by TysonMN** [comment]
Part 2 of 2: "Select" self, all children recursively, and all parents recursively

See commit https://github.com/TysonMN/Elmish.WPF/commit/69bc5ba8b1b4854cac8b43df4a6793617f70dd75

**Comment by ScottHutchinson** [comment]
@TysonMN Thank you once again for your help. Regarding Part 1, I'm very confused by your new `RoseTree.map` function, which appears to return a function, whereas my `traverse` function returns a `RoseTree`. So I'm not sure how to use your new function everywhere I was calling the `traverse` function. Shouldn't a true map function return a `RoseTree`?

**Comment by TysonMN** [comment]
I think you are confused about the difference between a function that is [curried](https://en.wikipedia.org/wiki/Currying) and one that is not.  Every function is F# is implicitly curried.  My `RoseTree.map` is explicitly curried.

The `->` symbol in F# (and, AFAIK in every language with this symbol) is [right associative](https://en.wikipedia.org/wiki/Operator_associativity), which means that
```fsharp
a -> b -> c
```

is the same as
```fsharp
a -> (b -> c)
```

Visual Studio says that the signature of my `RoseTree.map` is
```fsharp
('a -> 'b) -> (RoseTree<'a> -> RoseTree<'b>)
```

which is equivalent to
```fsharp
('a -> 'b) -> RoseTree<'a> -> RoseTree<'b>
```

by the right associativity of `->`.`

You are correct that your `traverse` function a bit different.  Its type signature is
```fsharp
('a -> 'a) -> 'a -> 'a
```

where `'a` has to be
```fsharp
RoseTree<Identifiable<Openable<Counter>>>
```

This is different from my `RoseTree.map` in three ways.
1. The type parameter of `RoseTree<>` is fixed (instead of working for any types).
2. The mapping function has the same input and output type (instead of having different types).
3. The mapping function is at the "same level" as the input (instead of "one level down").

The simplest way to implement a function with signature `('a -> 'a) -> 'a -> 'a` is to use (exactly) F#'s [backward pipe operator](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/functions/#:~:text=Backward%20pipeline%20operator).  That is not what you did though.  Instead, `RoseTree<>` is a recursive type, and `traverse` maps everything in that tree starting at the children of the root (i.e the nodes at depth 1); it does not map the data of the root node.

When I replaced `traverse` with `RoseTree.map`, the root node was now incremented by 2 each time instead of only 1.  I didn't care about that difference though, but I should have pointed that difference out in my comment.

If you would have implemented `traverse f a` as `f <| a`, then I think the data in the root would have been mapped as well.

**Comment by TysonMN** [comment]
And then since you weren't changing the structure of the tree, you might as well drop the mapping function down a level (i.e. change it's signature so it's input type is the type of data in the tree).  Lastly, extract out the actual mapping (so this function can handle `RoseTree<'a>` for any `'a`.  Then you have my `RoseTree.map`.

**Comment by TysonMN** [comment]
> If you would have implemented `traverse f a` as `f <| a`, then I think the data in the root would have been mapped as well.

Oh, that is not correct since `traverse` is where the recursion is.  (Being wrong there is what I get for trying to add some last idea there without thinking it through.)

**Comment by ScottHutchinson** [comment]
It turns out that I'm finding it quite difficult to implement Part 1 into my existing code without changing the behavior or getting a run-time null reference exception. I also don't like how you implemented the `RoseTree.map` function using explicit currying. So I'm going to try to implement Part 2 without doing Part 1. By the way, Don Syme discourages the use of the backward pipe operator, because it usually makes the code more difficult to read than using parentheses instead.

**Comment by ScottHutchinson** [comment]
Man, adding this `InOutMsg` onto an existing application is not much fun. The subTree Bindings were confusing enough before this. My application has about 22 subTree Bindings all of which need to be modified to add `InOutMsg`.

**Comment by ScottHutchinson** [comment]
@TysonMN , I don't seem to have `Binding.mapModel` in Elmish.WPF 3.5.6. I guess I will need to upgrade.

**Comment by TysonMN** [comment]
> It turns out that I'm finding it quite difficult to implement Part 1 into my existing code without changing the behavior or getting a run-time null reference exception.

How are you getting null reference exceptions?  That problem seems unrelated to the code I wrote.

> I also don't like how you implemented the `RoseTree.map` function using explicit currying.

That doesn't matter at all.  To curry implicitly, replace
```fsharp
let map f =
      let rec loop t =
          { Data = f t.Data
            Children = t.Children |> List.map loop }
      loop
```

with
```fsharp
let map f t =
      let rec loop t =
          { Data = f t.Data
            Children = t.Children |> List.map loop }
      loop t
```

It works exactly the same.

> By the way, Don Syme discourages the use of the backward pipe operator, because it usually makes the code more difficult to read than using parentheses instead.

I am aware.  I used it because I think that code is more readable using a backwards pipe than with parentheses, but I also understand that this is subjective.

> Elmish.WPF 3.5.8 doesn't seem to have a public `Binding.mapModel` function either.

Correct.  It was made public in the beta.

> So I'm supposed to upgrade to a beta release to get that? Seems sketchy.

The beta is solid.  It is still in beta because I might still make breaking changes to the API introduced in the beta.

> Man, adding this `InOutMsg` onto an existing application is not much fun. The subTree Bindings were confusing enough before this. My application has about 22 subTree Bindings all of which need to be modified to add `InOutMsg`.
> ...
> I don't seem to have `Binding.mapModel` in Elmish.WPF 3.5.6. I guess I will need to upgrade.

I definitely recommend upgrading.  The functional binding API I have added in the beta is very powerful.  It doesn't matter how many bindings you have.  Put them in a list and then write
```fsharp
|> Bindings.mapMsg InOutMsg.In
```

to lift all of the messages.  The function binding API also simplifies the code needed to define a `SubModelSeq` binding.

**Comment by ScottHutchinson** [comment]
> It doesn't matter how many bindings you have. Put them in a list and then write
> 
> ```fsharp
> |> Bindings.mapMsg InOutMsg.In
> ```
> 
> to lift all of the messages.

@TysonMN , I have attempted to do as you suggested in several commits to [my elmishwpfv4 branch](https://github.com/ScottHutchinson/StructFilters/tree/elmishwpfv4), but there are two type mismatch compiler errors that I don't know how to fix. I think the problems are all in the `fieldBindings` function.
```
1>C:\Users\scott\source\StructFilters\NG-DART.StructFilters\StructFilters.fs(348,26): error FS0001: Type mismatch. Expecting a    'Binding<(Model * SelfWithParent<RoseTree<FieldData>>),InOutMsg<RoseTreeMsg<FieldId,SubtreeMsg>,SubtreeOutMsg>> list'    but given a    'Binding<(Model * ('a * RoseTree<FieldData>)),InOutMsg<RoseTreeMsg<'b,SubtreeMsg>,'c>> list'    The type 'SelfWithParent<RoseTree<FieldData>>' does not match the type ''a * RoseTree<FieldData>'
1>C:\Users\scott\source\StructFilters\NG-DART.StructFilters\StructFilters.fs(350,37): error FS0001: Type mismatch. Expecting a    'unit -> Binding<'a,'b> list'    but given a    'int -> unit -> Binding<(Model * SelfWithParent<RoseTree<FieldData>>),InOutMsg<RoseTreeMsg<FieldId,SubtreeMsg>,SubtreeOutMsg>> list'    The type 'unit' does not match the type 'int'
```

**Comment by TysonMN** [comment]
> > Man, adding this `InOutMsg` onto an existing application is not much fun. The subTree Bindings were confusing enough before this. My application has about 22 subTree Bindings all of which need to be modified to add `InOutMsg`.
> 
> It doesn't matter how many bindings you have. Put them in a list and then write
> 
> ```fsharp
> |> Bindings.mapMsg InOutMsg.In
> ```
> 
> to lift all of the messages.

My point there is that you don't have to do the same thing 22 times.  Instead, the composable binding API allows that work to be deduplicated.

> I have attempted to do as you suggested in several commits to [my elmishwpfv4 branch](https://github.com/ScottHutchinson/StructFilters/tree/elmishwpfv4), but there is one type mismatch compiler error that I don't know how to fix.

When using `Bindings.mapMsg`?

If so, then don't let this get in your way.  If you can't get your 22 bindings working when using `BIndings.mapMsg`, but you can get them working after changing each one individually, then do that.

**Comment by ScottHutchinson** [comment]
@TysonMN , I managed to fix each of the 22 bindings one at a time in just a few minutes or so. Now [my elmishwpfv4 branch](https://github.com/ScottHutchinson/StructFilters/tree/elmishwpfv4) builds and runs as expected. Thank you so much for all your help.
