### ISSUE TITLE
Weird binding behaviour

### ISSUE THREAD

**Issue by francotiveron** [elmish/Elmish.WPF#545]
**High-level description**
Strange behaviour in binding

In my application I have a label bound to "MdpsCount"

```
let mutable i = 0

let bindings() : Binding<Model, Msg> list = [
    "Product" |> Binding.oneWay (fun m -> m.Product) 
    //"MdpsCount" |> Binding.oneWay (fun m -> (Repo.getData m.Product).Mdps.Count) ]
    //"MdpsCount" |> Binding.oneWay (fun m -> 
    //    let d = Repo.getData m.Product
    //    let q = d.Mdps
    //    let n  = q.Count
    //    n) 
    "MdpsCount" |> Binding.oneWay (fun m -> 
        let d = Repo.getData m.Product
        let q = d.Mdps
        let n  = q.Count
        i <- i + 1
        printfn "i = %d  n = %d" i n
        i) 
    ]
```
Every time the binding is called, i is incremented and the label shows the value. Moreover another integer n is calculated. Both value are printed in the console to check the real value

![image](https://user-images.githubusercontent.com/8280970/201288111-173e71ad-5032-4200-abfd-93beec5aa6ad.png)

The label shows the same value as the console.

![image](https://user-images.githubusercontent.com/8280970/201288025-5035516b-b342-4434-b789-3b5ee5d2f103.png)

Now I replace the return value from i to n

```
let mutable i = 0

let bindings() : Binding<Model, Msg> list = [
    "Product" |> Binding.oneWay (fun m -> m.Product) 
    //"MdpsCount" |> Binding.oneWay (fun m -> (Repo.getData m.Product).Mdps.Count) ]
    //"MdpsCount" |> Binding.oneWay (fun m -> 
    //    let d = Repo.getData m.Product
    //    let q = d.Mdps
    //    let n  = q.Count
    //    n) 
    "MdpsCount" |> Binding.oneWay (fun m -> 
        let d = Repo.getData m.Product
        let q = d.Mdps
        let n  = q.Count
        i <- i + 1
        printfn "i = %d  n = %d" i n
        n) 
    ]
```

Console is like before. The label in the window instead stays at 0

![image](https://user-images.githubusercontent.com/8280970/201288352-f551e6a4-5e4d-4723-a267-9c5fd4e1e492.png)

**Comment by TysonMN** [comment]
Can you share a link to a GitHub repo with executable code that reproduces the problem?  Ideally this reproduction is also minimal.

**Comment by francotiveron** [comment]
Please see https://github.com/francotiveron/Yatp.Desktop. It's not the main project (cannot make it public), but a simple repro 1

**Comment by marner2** [comment]
So the problem is that `Repo.getData` is storing stuff outside of the model. Elmish.WPF works assuming that all of the data is stored on the model, so that it can compare the old model to the new model to detect if it should signal a changed value. In this case, it's comparing the old model with the new model and both of them are returning the new value.

Another way you could solve this is by just making `MdpsCount` *always* issue an update by using `(Binding.OneWay.id >> Binding.mapModel (fun m -> ...))` instead of `Binding.oneWay (fun m -> ...)` (`Binding.oneWay` adds the equality check mentioned above by default - the second version doesn't).

**Comment by francotiveron** [comment]
Sorry, it doesn't make sense to me:
1) Repo.getData doesn't store anything, it just reads something
2) The binding function gets executed, so comparing old and new model is not relevant
3) If I replace n with i as return value of the binding function, it works even if i is not in the model
4) If you pull the las commit, I changed the app with the value in the model. Based on what you say it should work, but it doesn't.

Please have a better look.

**Comment by marner2** [comment]
The current problem is that you are returning the original model on line 27 of `Program.fs`. Change that to update the sub model and it will work. Something like:

```fsharp
    | ChartMsg (Chart.NewData product) ->
        let newChart = Chart.update (Chart.NewData product) m.Charts[product]
        { m with Charts = m.Charts.Change(product, (fun _ -> Some newChart)) }
```

To explain your other questions:
1. `Repo.getData` gets a value that is modified on line 18 of `Chart.fs` under the `NewData product` update case, and that modified value isn't stored anywhere on the model.
2. The binding function gets executed twice after Elmish calls your `update` function, once to get the value from the old model, and once to get the value from the new model. If those two are not the same, then Elmish will give WPF a `NotifyPropertyChanged` event with the name of the property. WPF then uses that event to call Get on that property (which calls the binding function a third time) and update the UI binding.
3. Using `i` just breaks the binding function the other way, because since it is incrementing between each call to the binding function Elmish will always see it as different, and therefore always give WPF a `NotifyPropertyChanged` event.
4. See top suggestion about updating the sub-model.
