### ISSUE TITLE
Binding.oneWayToSource

### ISSUE THREAD

**Issue by ChernayaKoshka** [elmish/Elmish.WPF#55]
Hello,

When working with textboxes in WPF, I continue to come across an issue. If I am typing too fast in a textbox control bound like so:

```XAML
<TextBox Text="{Binding Path=ImportantText, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"/>
```
```F#
        "ImportantText"
        |> Binding.twoWay
            (fun m -> m.ImportantText)
            (fun it _ -> it |> ImportantText)
```
Then there comes an issue where the Elmish.WPF is still updating the UI in the backend while the user is still entering data. What this means is, the users' caret goes to the beginning of the textbox, causing them to "type behind" the newly updated text. For an example of this issue, you can type quickly in the NewWindow sample.

I feel that the solution is to support `Binding.oneWayToSource`, which would mean that the code behind has no impact on the view (as there is no point to it anyway). Unless, of course, there is already a solution implemented that I am unaware of.

In the meantime, assuming that there is no particular reason the view needs to be updated as the user is typing, then a potential solution is to use WPF with InputBindings like so:

```XAML
<TextBox Text="Test">
    <TextBox.InputBindings>
        <KeyBinding Command="{Binding ImportantText}" Key="Return" />
        <KeyBinding Command="{Binding ImportantText}" Key="Enter" />
    </TextBox.InputBindings>
</TextBox>
``` 
Or a command binding attached to a "submit" button.

Thoughts?

**Comment by cmeeren** [comment]
This is indeed a problem if you use `UpdateSourceTrigger=PropertyChanged`. I have previously discussed the underlying issue at length in #40. As far as I know, there is no good way to fix this due to the underlying issue being entirely general in nature.

I haven't tested, but I think setting `Mode=OneWayToSource` should work when you have defined `Binding.twoWay`. In any case, setting `Mode=OneWayToSource` means that the model can not easily control what is shown in the `TextBox`. This might be a problem for setting initial values in the fields, but there might be other ways around that. I haven't thought too hard about it yet.

Another quick solution if you don't need to update anything as you type, is simply to remove `UpdateSourceTrigger=PropertyChanged`. It will then update when the `TextBox` loses focus.

**Comment by cmeeren** [comment]
> For an example of this issue, you can type quickly in the NewWindow sample.

Note that there's a big difference between Debug and Release modes, particularly if you have any kind of Elmish.WPF logging turned on ( `Program.withConsoleTrace` or an `ElmConfig` with logging).

**Comment by ChernayaKoshka** [comment]
It appears setting the binding mode to `OneWayToSource` and using `binding.twoWay` has solved my problem completely. The performance difference between debug/release modes is good to keep in mind. I appreciate your timely response. Given this is a duplicate of #40 I will go ahead and close this and continue any further discussion in that issue.
