### ISSUE TITLE
Best way to implement "Statically-typed view model" approach?

### ISSUE THREAD

**Issue by YkTru** [elmish/Elmish.WPF#589]
I'm having trouble understanding how to implement the _statically-typed view model_ approach. (everything is working fine with the _bindings_ approach)

I attempted to use the guidance from [Elmish.WPF on GitHub](https://github.com/elmish/Elmish.WPF), but despite spending a lot of time on it, I find the documentation either unclear or possibly outdated. Is there a *complete* and current sample that demonstrates the best way to do this?

I've been working on this implementation, but regardless of my efforts, the 'HelloViewModel' does not appear in Intellisense. Here's my attempt: https://github.com/YkTru/ElmishWPF_StaticallyTypedViewModel.

Any assistance would be greatly appreciated. Thank you.

**Comment by YkTru** [comment]
@TysonMN @marner2 

I'm sorry to bother you, but am I doing anything wrong? Thank you.

**Comment by marner2** [comment]
Ahh, I see what the problem is. Yes, your View Model cannot be inside a module, as XAML doesn't support nested types (F# modules are implemented as types in .NET). This slightly complicates your simple example, as you'll have to split things up into several modules.

Take your view model and put it outside and after the `zApp` module, then put the main function inside another module after the view model. You'll also need to move the Elmish.WPF open under the namespace.

I'll work on making the documentation clearer with an explicit section in the docs around this feature.

The example of this is in [`SubModelStatic.Core`](https://github.com/elmish/Elmish.WPF/blob/master/src/Samples/SubModelStatic.Core/Program.fs). It's a bit more involved as I wanted to illustrate how you get nested auto-completions in the wpf xaml designer if you use this method.

Let me know if you have any more questions or suggestions!

**Comment by YkTru** [comment]
It works, thanks a lot!

1. I've created a new sample with more relevant State/Msg; do you want me to share it so you can review it, and then maybe add it to the Elmish.WPF samples?

I must mention, as a newcomer transitioning directly from C#+MVVM, such a sample would have saved me a great deal of time and effort. (I guess from the documentation any F# programmer would have figured it out rapidly, but for anyone in a learning process I think it might no be as evident)

---

2. Do you personally recommend/prefer the _bindings_ approach or the _statically-typed VM_ one? I obviously lean towards the _bindings_ approach for readability, but I assume that _typed XAML bindings_ are way more advantageous than those based on strings?

I'm asking since in the samples, clearly the _bindings_ approach is preferred, so does it have any advantages versus the other one other than readability and a more "functionnal" style?

Thank you again

**Comment by LyndonGingerich** [comment]
@YkTru

If you have a sample to suggest already made, by all means share it. Even if we don't use it directly, it could inspire ideas.

The "view model class" approach is relatively new, which is why the "binding list" approach has many more samples. If you use view model classes, you will be able to navigate from XAML binding usages to their definitions in Rider and Visual Studio. Rider will also check XAML when you search for usages. I don't think that the "binding list" approach has any particular advantages, but we will keep it around to avoid breaking existing code.

**Comment by YkTru** [comment]
Here: https://github.com/YkTru/Elmish.WPF-Samples-ViewModel/tree/master

**1. Aspects I'm uncertain about that might need further refinement:**
- _Solution + Project + Namespace names_: Should I add a "Static" suffix for the sample? 
- _"ViewModel" namespace_: I guess the name should ideally be "Program", but I chose this to emphasize ViewModel as the main aspect of the sample.
- _Scaling_: Is the best approach to add a "ViewModel" file containing all ViewModels, and then a file named "Main" for bootstrapping, placed just below? Should all seperate component (MVU Program) be responsible for the VM definition, or putting it all in a single file (even for large project) is advised?
- _Readability_: for the ViewModel section, I don't like that "open" are floating around, it obliges me to visually separate the code using comments which IMO add noise. Again I guess putting the VM and Main in another files would resolve that "issue"?
- 
    
**2. Suggestions for samples refinement:**
- _Project ViewModel.WPF_: In all your samples, you omit ".WPF". However, in VS2022, it places the Core project under the WPF project, which I think is not ideal (unless I'm missing something?).
- _Elmish.WPF concepts_ : I've made my sample more abstract (e.g., using 'FieldValue' and 'Event' instead of a more concrete Counter example), so it's easier for those familiar with C#+MVVM to more easily grasp the essential concepts (is 'Event' a suitable and adequate name?).

**Comment by TysonMN** [comment]
> Do you personally recommend/prefer the bindings approach or the statically-typed VM one? I obviously lean towards the bindings approach for readability, but I assume that typed XAML bindings are way more advantageous than those based on strings?

(We having been calling them dynamic bindings and static bindings.)

I prefer dynamic bindings, but I stopped using Elmish.WPF (due to job change) before static bindings were created.
