### ISSUE TITLE
"TwoWayT" and "OneWaySeqT" binding not showing (Version 4.0.0-beta-54)

### ISSUE THREAD

**Issue by YkTru** [elmish/Elmish.WPF#605]
```xml
  <ItemGroup>
    <PackageReference Include="Elmish.WPF" Version="4.0.0-beta-54" />
    <PackageReference Include="Serilog" Version="3.1.1" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="2.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
  </ItemGroup>
```
![x](https://github.com/elmish/Elmish.WPF/assets/125092692/31532497-a909-4f22-a649-2701c7444d5f)

![2024-05-30_153328](https://github.com/elmish/Elmish.WPF/assets/125092692/168ba137-aa83-4ce3-96c3-4d14eb162917)

- I tried 4.0.0-beta-55, but it says "unable to find"
- and in the first sample when I try to use the untyped TwoWay, addLazy.id become red (why?)

Thank you

**Comment by YkTru** [comment]
@marner2 am I doing something wrong? thanks

**Comment by marner2** [comment]
@YkTru Nope you're not doing anything wrong. I think the issue is just that I failed to push a beta with that change. I'll try to get that soon.

Meanwhile if you need to make it work with beta-54, use OneWayT for the getter and OneWayToSourceT for the setter on the two-way property and it will work. For the oneWaySeq just use the non-T version for now.

**Comment by marner2** [comment]
@YkTru You should be able to install 4.0.0-beta-55 and it should have these new bindings.
