### ISSUE TITLE
UWP support

### ISSUE THREAD

**Issue by JaggerJo** [elmish/Elmish.WPF#69]
Are there any plans towards supporting UWP ?

_(Or is the a simple solution to just setup the "Program" for UWP instead of WPF ?)_

**Comment by et1975** [comment]
UWP is supported via React Native.

**Comment by cmeeren** [comment]
There are currently no plans for Elmish.WPF to support UWP. It would need to be a separate library, since (I guess) the UI frameworks use different assemblies. If anyone is willing to create and maintain that, I could probably extract the binding/view model logic from Elmish.WPF, so that part can be re-used. However, there might be WPF-specific optimizations or design choices even in this code, since it was never made with UWP in mind.

That said: Elmish.WPF is based on static (XAML-defined) views, and the Elmish `view` function only creates the bindings (i.e. the view models). This has some significant drawbacks compared to "real" Elmish with dynamic UIs, which I have elaborated a bit on in a few other issues in this repo. So I guess people would be better off with a solution based on dynamic UI generation.

**Comment by JaggerJo** [comment]
I looked into it and think there is a lot of code that could be shared between UWP and WPF as they rely on the same interfaces ('INotifyPropertyChanged' & 'ICommand'). Sadly 'INotifyDataErrorInfo' is not present in UWP.

I am looking into this.

**Comment by FoggyFinder** [comment]
> F# support on UWP is really bad. You can reference a F# project from UWP but the opposite doesn't seem to work at all. 

F# support on UWP is really bad. But it is possible to use F# there anyway.

**Comment by TysonMN** [comment]
Has anything changed with this?  Is there a library that depends on Elmish just like Elmish.WPF does but is for UWP instead of WPF?

**Comment by cmeeren** [comment]
> Is there a library that depends on Elmish just like Elmish.WPF does but is for UWP instead of WPF?

I don't know of any such library. I haven't kept track, though I couldn't find anything after a bit of cursory googling.
